create table if not exists public.mixforge_stem_usage (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  stem_count smallint not null check (stem_count between 1 and 6),
  created_at timestamptz not null default now()
);

alter table public.mixforge_stem_usage enable row level security;

create index if not exists mixforge_stem_usage_ip_created_idx
  on public.mixforge_stem_usage (ip_hash, created_at desc);

revoke all on table public.mixforge_stem_usage from anon, authenticated;

grant all on table public.mixforge_stem_usage to service_role;

comment on table public.mixforge_stem_usage is
  'Server-only rolling usage ledger for MixForge stem-separation cost controls.';
